baseURL = "https://MariaEriksson.github.io/"
languageCode = "en-gb"
theme = "anatole"
enableEmoji = true

[params]
title = "Maria Eriksson"
author = "MariaEriksson"
description = "Postdoctoral Researcher | Epilepsy Surgery in Children"
profilePicture = "images/profile_pic.png"
fullPostContent = "true"

[menu]
  [[menu.main]]
  name = "About me"
  identifier = "about"
  weight = 100
  url = "/about/"

  [[menu.main]]
  name = "Work"
  weight = 200
  identifier = "work"
  url = "/work/"

  [[menu.main]]
  name = "Publications"
  weight = 300
  identifier = "publications"
  url = "/publications/"
